parameters:
- name: newsubnet
  type: string

trigger: none

jobs:
- job: build
  displayName: build
  steps:
  - script: echo building $(Build.BuildNumber) with ${{ parameters.newsubnet }}
  - task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment example: Resource Group scope'
  inputs:
    azureResourceManagerConnection: demoSC
    subscriptionId: 'd66af87f-6456-4537-9389-f23d8e64f39e'
    resourceGroupName: rgCLI
    location: 'East US'
    templateLocation: 'Linked artifact' 
    csmFile: subnetexample.json
